// ── Mermaid Theme Configuration ────────────────────────────────────────────────

export interface MermaidThemeConfig {
  theme: 'default' | 'dark' | 'forest' | 'neutral' | 'base';
  themeVariables?: Record<string, string>;
  securityLevel?: 'strict' | 'loose' | 'antiscript';
  startOnLoad?: boolean;
  fontFamily?: string;
  fontSize?: number;
}

export const LIGHT_THEME: MermaidThemeConfig = {
  theme: 'base',
  themeVariables: {
    background: '#ffffff',
    primaryColor: '#f3f4f6',
    primaryBorderColor: '#9ca3af',
    primaryTextColor: '#111827',
    lineColor: '#6b7280',
    secondaryColor: '#f9fafb',
    tertiaryColor: '#ffffff',
    fontSize: '14px',
    fontFamily: 'Inter, -apple-system, system-ui, sans-serif',
    mainBkg: '#ffffff',
    nodeBorder: '#d1d5db',
    clusterBkg: '#f9fafb',
    clusterBorder: '#d1d5db',
    titleColor: '#111827',
    edgeLabelBackground: '#ffffff',
    nodeTextColor: '#111827',
    actorBorder: '#9ca3af',
    actorBkg: '#f3f4f6',
    actorTextColor: '#111827',
    actorLineColor: '#6b7280',
    signalColor: '#6b7280',
    signalTextColor: '#6b7280',
    labelBoxBkgColor: '#f3f4f6',
    labelBoxBorderColor: '#9ca3af',
    labelTextColor: '#111827',
    loopTextColor: '#6b7280',
    noteBorderColor: '#d1d5db',
    noteBkgColor: '#f9fafb',
    noteTextColor: '#111827',
    activationBorderColor: '#9ca3af',
    activationBkgColor: '#f3f4f6',
    sequenceNumberColor: '#6b7280',
    sectionBkgColor: '#f9fafb',
    altSectionBkgColor: '#ffffff',
    sectionBkgColor1: '#f9fafb',
    sectionBkgColor2: '#ffffff',
    taskBorderColor: '#9ca3af',
    taskBkgColor: '#f3f4f6',
    taskTextColor: '#111827',
    taskTextOutsideColor: '#6b7280',
    taskTextClickableColor: '#6b7280',
    activeTaskBorderColor: '#6b7280',
    activeTaskBkgColor: '#d1d5db',
    gridColor: '#e5e7eb',
    doneTaskBkgColor: '#f3f4f6',
    doneTaskBorderColor: '#9ca3af',
    critBorderColor: '#dc2626',
    critBkgColor: '#fef2f2',
    todayLineColor: '#dc2626',
    classText: '#111827',
    fillType0: '#ffffff',
    fillType1: '#f9fafb',
    fillType2: '#f3f4f6',
    fillType3: '#f9fafb',
    fillType4: '#ffffff',
    fillType5: '#f3f4f6',
    fillType6: '#f9fafb',
    fillType7: '#ffffff',
    fillType8: '#f3f4f6',
  },
};

export const DARK_THEME: MermaidThemeConfig = {
  theme: 'base',
  themeVariables: {
    background: '#111111',
    primaryColor: '#334155',
    primaryBorderColor: '#94a3b8',
    primaryTextColor: '#f8fafc',
    lineColor: '#94a3b8',
    secondaryColor: '#1e293b',
    tertiaryColor: '#111111',
    fontSize: '14px',
    fontFamily: 'Inter, -apple-system, system-ui, sans-serif',
    mainBkg: '#111111',
    nodeBorder: '#64748b',
    clusterBkg: '#1e293b',
    clusterBorder: '#64748b',
    titleColor: '#f8fafc',
    edgeLabelBackground: '#1e293b',
    nodeTextColor: '#f8fafc',
    actorBorder: '#64748b',
    actorBkg: '#334155',
    actorTextColor: '#f8fafc',
    actorLineColor: '#94a3b8',
    signalColor: '#60a5fa',
    signalTextColor: '#93c5fd',
    labelBoxBkgColor: '#1e293b',
    labelBoxBorderColor: '#64748b',
    labelTextColor: '#f8fafc',
    loopTextColor: '#94a3b8',
    noteBorderColor: '#64748b',
    noteBkgColor: '#1e293b',
    noteTextColor: '#f8fafc',
    activationBorderColor: '#64748b',
    activationBkgColor: '#334155',
    sequenceNumberColor: '#94a3b8',
    sectionBkgColor: '#1e293b',
    altSectionBkgColor: '#111111',
    sectionBkgColor1: '#1e293b',
    sectionBkgColor2: '#111111',
    taskBorderColor: '#64748b',
    taskBkgColor: '#334155',
    taskTextColor: '#f8fafc',
    taskTextOutsideColor: '#94a3b8',
    taskTextClickableColor: '#60a5fa',
    activeTaskBorderColor: '#60a5fa',
    activeTaskBkgColor: '#1e3a5f',
    gridColor: '#1e293b',
    doneTaskBkgColor: '#1e293b',
    doneTaskBorderColor: '#64748b',
    critBorderColor: '#fb7185',
    critBkgColor: '#3b1a1a',
    todayLineColor: '#fb923c',
    classText: '#f8fafc',
    fillType0: '#334155',
    fillType1: '#1e3a5f',
    fillType2: '#3b2f2f',
    fillType3: '#1e293b',
    fillType4: '#2d3748',
    fillType5: '#3a3a1e',
    fillType6: '#3a2a3a',
    fillType7: '#1e293b',
    fillType8: '#2d3748',
  },
};

export function getMermaidConfig(theme: 'light' | 'dark'): MermaidThemeConfig {
  return theme === 'dark' ? DARK_THEME : LIGHT_THEME;
}
