// ── Mermaid Theme Configuration ────────────────────────────────────────────────

export interface MermaidThemeConfig {
  theme: 'default' | 'dark' | 'forest' | 'neutral' | 'base';
  themeVariables?: Record<string, string>;
  securityLevel?: 'strict' | 'loose' | 'antiscript';
  startOnLoad?: boolean;
  fontFamily?: string;
  fontSize?: number;
}

export const LIGHT_THEME: MermaidThemeConfig = {
  theme: 'base',
  themeVariables: {
    background: '#ffffff',
    primaryColor: '#f3f4f6',
    primaryBorderColor: '#9ca3af',
    primaryTextColor: '#111827',
    lineColor: '#6b7280',
    secondaryColor: '#f9fafb',
    tertiaryColor: '#ffffff',
    fontSize: '14px',
    fontFamily: 'Inter, -apple-system, system-ui, sans-serif',
    mainBkg: '#ffffff',
    nodeBorder: '#d1d5db',
    clusterBkg: '#f9fafb',
    clusterBorder: '#d1d5db',
    titleColor: '#111827',
    edgeLabelBackground: '#ffffff',
    nodeTextColor: '#111827',
    actorBorder: '#9ca3af',
    actorBkg: '#f3f4f6',
    actorTextColor: '#111827',
    actorLineColor: '#6b7280',
    signalColor: '#6b7280',
    signalTextColor: '#6b7280',
    labelBoxBkgColor: '#f3f4f6',
    labelBoxBorderColor: '#9ca3af',
    labelTextColor: '#111827',
    loopTextColor: '#6b7280',
    noteBorderColor: '#d1d5db',
    noteBkgColor: '#f9fafb',
    noteTextColor: '#111827',
    activationBorderColor: '#9ca3af',
    activationBkgColor: '#f3f4f6',
    sequenceNumberColor: '#6b7280',
    sectionBkgColor: '#f9fafb',
    altSectionBkgColor: '#ffffff',
    sectionBkgColor1: '#f9fafb',
    sectionBkgColor2: '#ffffff',
    taskBorderColor: '#9ca3af',
    taskBkgColor: '#f3f4f6',
    taskTextColor: '#111827',
    taskTextOutsideColor: '#6b7280',
    taskTextClickableColor: '#6b7280',
    activeTaskBorderColor: '#6b7280',
    activeTaskBkgColor: '#d1d5db',
    gridColor: '#e5e7eb',
    doneTaskBkgColor: '#f3f4f6',
    doneTaskBorderColor: '#9ca3af',
    critBorderColor: '#dc2626',
    critBkgColor: '#fef2f2',
    todayLineColor: '#dc2626',
    classText: '#111827',
    fillType0: '#ffffff',
    fillType1: '#f9fafb',
    fillType2: '#f3f4f6',
    fillType3: '#f9fafb',
    fillType4: '#ffffff',
    fillType5: '#f3f4f6',
    fillType6: '#f9fafb',
    fillType7: '#ffffff',
    fillType8: '#f3f4f6',
  },
};

export const DARK_THEME: MermaidThemeConfig = {
  theme: 'base',
  themeVariables: {
    background: '#1f1f1f',
    primaryColor: '#2d2d2d',
    primaryBorderColor: '#6b7280',
    primaryTextColor: '#e5e7eb',
    lineColor: '#6b7280',
    secondaryColor: '#272727',
    tertiaryColor: '#1f1f1f',
    fontSize: '14px',
    fontFamily: 'Inter, -apple-system, system-ui, sans-serif',
    mainBkg: '#1f1f1f',
    nodeBorder: '#4b5563',
    clusterBkg: '#272727',
    clusterBorder: '#4b5563',
    titleColor: '#e5e7eb',
    edgeLabelBackground: '#272727',
    nodeTextColor: '#e5e7eb',
    actorBorder: '#6b7280',
    actorBkg: '#2d2d2d',
    actorTextColor: '#e5e7eb',
    actorLineColor: '#6b7280',
    signalColor: '#6b7280',
    signalTextColor: '#6b7280',
    labelBoxBkgColor: '#2d2d2d',
    labelBoxBorderColor: '#6b7280',
    labelTextColor: '#e5e7eb',
    loopTextColor: '#6b7280',
    noteBorderColor: '#4b5563',
    noteBkgColor: '#272727',
    noteTextColor: '#e5e7eb',
    activationBorderColor: '#6b7280',
    activationBkgColor: '#2d2d2d',
    sequenceNumberColor: '#6b7280',
    sectionBkgColor: '#272727',
    altSectionBkgColor: '#1f1f1f',
    sectionBkgColor1: '#272727',
    sectionBkgColor2: '#1f1f1f',
    taskBorderColor: '#6b7280',
    taskBkgColor: '#2d2d2d',
    taskTextColor: '#e5e7eb',
    taskTextOutsideColor: '#6b7280',
    taskTextClickableColor: '#9ca3af',
    activeTaskBorderColor: '#9ca3af',
    activeTaskBkgColor: '#4b5563',
    gridColor: '#374151',
    doneTaskBkgColor: '#2d2d2d',
    doneTaskBorderColor: '#6b7280',
    critBorderColor: '#f87171',
    critBkgColor: '#2d1b1b',
    todayLineColor: '#f87171',
    classText: '#e5e7eb',
    fillType0: '#1f1f1f',
    fillType1: '#272727',
    fillType2: '#2d2d2d',
    fillType3: '#272727',
    fillType4: '#1f1f1f',
    fillType5: '#2d2d2d',
    fillType6: '#272727',
    fillType7: '#1f1f1f',
    fillType8: '#2d2d2d',
  },
};

export function getMermaidConfig(theme: 'light' | 'dark'): MermaidThemeConfig {
  return theme === 'dark' ? DARK_THEME : LIGHT_THEME;
}
